// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQL4MsiyJFkJ4_0sDP4NJw6Zf2c3YWuvw',
    appId: '1:944308767853:web:c5bba1414d2acf57c28364',
    messagingSenderId: '944308767853',
    projectId: 'sport-project-623a2',
    authDomain: 'sport-project-623a2.firebaseapp.com',
    storageBucket: 'sport-project-623a2.appspot.com',
    measurementId: 'G-0C5JEGTPKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWFJQ2w4-fYYSwXz64RMhDmzCIhJzyxo4',
    appId: '1:944308767853:android:c2e193e0e1be67b4c28364',
    messagingSenderId: '944308767853',
    projectId: 'sport-project-623a2',
    storageBucket: 'sport-project-623a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEmxUz49c9m1uYF23rh6J_XnpBU1dgYYQ',
    appId: '1:944308767853:ios:1632009e92260b93c28364',
    messagingSenderId: '944308767853',
    projectId: 'sport-project-623a2',
    storageBucket: 'sport-project-623a2.appspot.com',
    iosBundleId: 'com.example.sportsProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEmxUz49c9m1uYF23rh6J_XnpBU1dgYYQ',
    appId: '1:944308767853:ios:7e927b24dfa5d3f2c28364',
    messagingSenderId: '944308767853',
    projectId: 'sport-project-623a2',
    storageBucket: 'sport-project-623a2.appspot.com',
    iosBundleId: 'com.example.sportsProject.RunnerTests',
  );
}
